### ISSUE TITLE
Add beautify Res option while splitting Res

### ISSUE THREAD

**Issue by ThePrimalPea** [Tre-VN/Tre#23]
Normally after splitted the original Res, they will look ugly because of aflags and time thingy. Then if you want to have them beautiful, you will need to merge them then split them again.

**Comment by harumazzz** [comment]
I will look forward to that. Thanks

**Comment by harumazzz** [comment]
Please keep this issue open while I am testing that. I will finish and then close later.

**Comment by harumazzz** [comment]
Starting from new version, the tool will have setting "remove_unused_info" in the setting. When you split with that on, the tool will delete all unused info that doesn't important with the game. I only included "aflag" and "time" since you've asked for that, if you having more key you can reply to this and I will include it here, I will close this issue for now.
![image](https://user-images.githubusercontent.com/114157573/221070842-a12f2a6c-1de0-4509-8ad8-a14ce699439a.png)
![image](https://user-images.githubusercontent.com/114157573/221070859-dd3aad4c-eee5-4cae-b74f-cba084ccf45a.png)
![image](https://user-images.githubusercontent.com/114157573/221071408-da0ea361-6b01-42b7-a883-aa633bcf42c4.png)
